# -*- coding: utf-8 -*-
"""process_tmdb_csv_2_jsonl

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13cQtZipOpws9aL_7-Mwt0tc2tARgPIFx
"""

import requests
import pandas as pd
import json

# Function to collapse genre names into a single string
def collapse_genres(genres_ids, genres_dict):
    genres = []
    for genre_id in genres_ids:
        genre_name = genres_dict.get(genre_id)
        if genre_name:
            genres.append(genre_name)
    return " ".join(sorted(genres))

# Function to combine features for the text column
def combine_features(row):
    try:
        return row['overview'] + " " + row["genres_name"]
    except Exception as e:
        print("Error:", e, row)

# Function to process TMDB movies CSV and convert to JSON
def process_tmdb_csv(input_file, output_file):
    movies = pd.read_csv(input_file)
    movies['genres_name'] = movies.apply(lambda x: collapse_genres(eval(x.genres), genres_dict), axis=1)

    for f in ['original_title', 'overview', 'genres_name']:
        movies[f] = movies[f].fillna('')

    movies["text"] = movies.apply(combine_features, axis=1)
    movies = movies[['id', 'original_title', 'text']]
    movies.rename(columns={'original_title': 'title', 'id': 'doc_id'}, inplace=True)

    movies['fields'] = movies.apply(lambda row: row.to_dict(), axis=1)
    movies['put'] = movies['doc_id'].apply(lambda x: f"id:hybrid-search:doc::{x}")

    df_result = movies[['put', 'fields']]
    print(df_result.head())
    df_result.to_json(output_file, orient='records', lines=True)

# Step 1: Fetch data from TMDB API
url = "https://api.themoviedb.org/3/discover/movie?include_adult=false&include_video=false&language=en-US&page=1&primary_release_year=2000&sort_by=popularity.desc"
headers = {
    "accept": "application/json",
    "Authorization": "Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJkMzlmMzIwOWIwMmJiNmZmOTAxMjhjYjE5NWJiOTg3ZCIsIm5iZiI6MTczMDY1MjMzNS41MTgzNDQ0LCJzdWIiOiI2NzI2NmMwZjdlOGZjNWE4MjFmOTE5M2QiLCJzY29wZXMiOlsiYXBpX3JlYWQiXSwidmVyc2lvbiI6MX0.ZY0ghNHwif5UxhqSGBZ71vxe9FQ7poq4vAyK7vWHkwU"
  # Replace YOUR_API_KEY with your actual API key
}

response = requests.get(url, headers=headers)
data = response.json()

# Step 2: Prepare a dictionary of genres (ID to name mapping)
genres_dict = {genre['id']: genre['name'] for genre in data.get('genres', [])}

# Extract movie data
movies_data = []
for movie in data['results']:
    movies_data.append({
        'id': movie['id'],
        'original_title': movie['original_title'],
        'overview': movie['overview'],
        'genres': json.dumps(movie['genre_ids'])  # Saving genre IDs as a JSON string
    })

# Create DataFrame and save to CSV
movies_df = pd.DataFrame(movies_data)
csv_file = "themoviedb_movies.csv"
movies_df.to_csv(csv_file, index=False)

# Step 3: Process the CSV file and convert to JSON
output_json_file = "clean_themoviedb.jsonl"
process_tmdb_csv(csv_file, output_json_file)